// Writes packages/config/abis.ts from the compiled contracts, so no ABI is ever written by hand (AGENTS.md §7).
//
//   cd packages/contracts && forge build && node script/export-abis.mjs
//   node script/export-abis.mjs --check     # exits 1 if abis.ts is out of date (for CI)
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "out");
const target = join(here, "..", "..", "config", "abis.ts");

// [contract name, exported constant]. Upfront's own contracts, then the external ones the app calls.
const contracts = [
  ["UpfrontHook", "upfrontHookAbi"],
  ["UpfrontLauncher", "upfrontLauncherAbi"],
  ["AdvanceDesk", "advanceDeskAbi"],
  ["LenderVault", "lenderVaultAbi"],
  ["IV4Quoter", "v4QuoterAbi"],
  ["IAllowanceTransfer", "permit2Abi"],
  ["IUniversalRouter", "universalRouterAbi"],
];

/** Finds out/<File>.sol/<Name>.json wherever the contract was compiled from. */
function artifactFor(name) {
  for (const dir of readdirSync(out)) {
    const file = join(out, dir, `${name}.json`);
    if (dir.endsWith(".sol") && existsSync(file)) return file;
  }
  throw new Error(`No compiled artifact for ${name}. Run forge build first.`);
}

let body = `// Generated by packages/contracts/script/export-abis.mjs from the compiled contracts. Do not edit by hand.\n`;
for (const [name, constant] of contracts) {
  const artifact = JSON.parse(readFileSync(artifactFor(name), "utf8"));
  body += `\nexport const ${constant} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {}
  if (current !== body) {
    console.error("packages/config/abis.ts is out of date. Run: node script/export-abis.mjs");
    process.exit(1);
  }
  console.log("abis.ts is up to date");
} else {
  writeFileSync(target, body);
  console.log(`Wrote ${target}`);
}
