// Writes packages/config/abis.ts from the compiled contracts, so no ABI is ever written by hand (AGENTS.md §7).
//
//   cd packages/contracts && forge build && node script/export-abis.mjs
//   node script/export-abis.mjs --check     # exits 1 if abis.ts is out of date (for CI)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "out");
const target = join(here, "..", "..", "config", "abis.ts");

const contracts = ["UpfrontHook", "UpfrontLauncher", "AdvanceDesk", "LenderVault"];

let body = `// Generated by packages/contracts/script/export-abis.mjs from the compiled contracts. Do not edit by hand.\n`;
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8"));
  const abi = artifact.abi;
  body += `\nexport const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {}
  if (current !== body) {
    console.error("packages/config/abis.ts is out of date. Run: node script/export-abis.mjs");
    process.exit(1);
  }
  console.log("abis.ts is up to date");
} else {
  writeFileSync(target, body);
  console.log(`Wrote ${target}`);
}
