// Generates src/content/faq.ts from the repository's FAQ.md, the single source for the website FAQ (DESIGN.md §3).
//   node scripts/sync-faq.mjs            writes the file
//   node scripts/sync-faq.mjs --check    exits 1 if it is out of date
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "../../FAQ.md");
const target = join(root, "src/content/faq.ts");

if (!existsSync(source)) {
  // A build that only has this package keeps the committed file.
  console.log("FAQ.md not found; keeping the committed src/content/faq.ts");
  process.exit(0);
}

const items = [];
for (const block of readFileSync(source, "utf8").split(/\n\s*\n/)) {
  const m = /^\*\*(.+?)\*\*\n([\s\S]+)$/.exec(block.trim());
  if (m) items.push({ q: m[1].trim(), a: m[2].replace(/\s*\n\s*/g, " ").trim() });
}
if (items.length === 0) throw new Error("No questions found in FAQ.md");

const body = `// Generated by scripts/sync-faq.mjs from FAQ.md. Do not edit by hand.\nexport const faq: { q: string; a: string }[] = ${JSON.stringify(items, null, 2)};\n`;

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== body) {
    console.error("src/content/faq.ts is out of date. Run: node scripts/sync-faq.mjs");
    process.exit(1);
  }
  console.log("faq.ts is up to date");
} else {
  writeFileSync(target, body);
  console.log(`Wrote ${items.length} questions`);
}
