// Generated by scripts/sync-faq.mjs from FAQ.md. Do not edit by hand.
export const faq: { q: string; a: string }[] = [
  {
    "q": "What is Upfront?",
    "a": "Upfront lets you launch a trading pool that pays you a fee on every trade, in USDG. Once your pool has a track record, you can get some of your future earnings today."
  },
  {
    "q": "Who is it for?",
    "a": "Creators, communities, trading apps and launchpads that want to earn from the trades they bring in. Traders who want honest fees. Lenders who want to earn from advances that repay themselves."
  },
  {
    "q": "How do I earn?",
    "a": "Launch a pool and choose its Upfront fee. Every trade in your pool pays that fee in USDG. You choose how it splits between you, your app, and whoever sends the trade (the referrer). If there's no referrer, that share is yours. Claim your earnings any time."
  },
  {
    "q": "What does \"upfront\" mean here?",
    "a": "After your pool has earned for a while, you get an offer: USDG now, repaid from a share of your future fees. You don't make payments. Every new trade repays a little until it's done. Then your full earnings come back to you."
  },
  {
    "q": "What happens if my pool earns less than expected?",
    "a": "Repayment just slows down. There's no interest clock and no collateral taken. If repayment falls far behind schedule, a larger share of your fees goes to repayment until it's caught up. If an advance is still unpaid about six months after its schedule, it's written off. That's a loss for lenders, and your pool is unlocked."
  },
  {
    "q": "How is my offer calculated?",
    "a": "From your pool's own earnings, using its weakest recent week, so a single good day can't inflate it. Offers last 24 hours and are recalculated each time."
  },
  {
    "q": "Can I change my fee later?",
    "a": "You can lower it at any time. You can never raise it. Traders always know the most they'll ever pay in your pool."
  },
  {
    "q": "As a trader, what will I pay?",
    "a": "Exactly the total fee shown before you confirm: the pool's trading fee plus the Upfront fee. There's no hidden cut."
  },
  {
    "q": "How do lenders earn?",
    "a": "Lenders deposit USDG. That money funds the upfront offers, and each one is repaid with a flat fee. Every advance and every repayment is visible on-chain."
  },
  {
    "q": "What are the risks for lenders?",
    "a": "A pool's trading can slow down or stop, so an advance can be repaid late or not in full. Advances are sized on a pool's weakest recent weeks to limit this, but lending always carries risk."
  },
  {
    "q": "Which network is Upfront on?",
    "a": "Arbitrum and Robinhood Chain (an Arbitrum chain). All fees and payouts are in USDG, the Paxos dollar."
  },
  {
    "q": "Which tokens can I launch a pool for?",
    "a": "Any token, paired with USDG, including Robinhood stock tokens."
  },
  {
    "q": "Do I need to hold ETH?",
    "a": "A small amount, for network fees."
  },
  {
    "q": "Can Upfront change my pool after launch?",
    "a": "No. Your fee can only go down, and only by you. Your split can't change. Nobody, including us, can move your balance."
  },
  {
    "q": "Is the code open?",
    "a": "Yes. The contracts and the app are open source, and every contract address is listed and verified on the explorer."
  }
];
